# Generated by Django 2.0.4 on 2018-06-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Treść')),
            ],
            options={
                'verbose_name': 'Zasady',
                'verbose_name_plural': 'Zasady',
                'abstract': False,
                'default_permissions': 'view',
            },
        ),
    ]
