# Generated by Django 3.2.4 on 2021-06-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='country',
            field=models.CharField(max_length=512, null=True, verbose_name='Kraj'),
        ),
    ]
