# Generated by Django 2.0.4 on 2018-05-28 13:17

from django.db import migrations, models
import system.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=system.models.OverwriteFileSystemStorage(location='../static/img/'), upload_to=system.models.upload_file_name, verbose_name='Zdjęcie'),
        ),
    ]
