# Generated by Django 2.0.4 on 2018-06-02 21:43

from django.db import migrations, models
import system.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20180528_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='nickname',
            field=models.CharField(default='', max_length=128, verbose_name='Nazwa użytkownika'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=system.models.OverwriteFileSystemStorage(location='d:/_info/__inne/projekty/typer/media/'), upload_to=system.models.upload_file_name, verbose_name='Zdjęcie'),
        ),
    ]
