# Generated by Django 3.2.4 on 2021-06-04 22:15

from django.db import migrations, models
import system.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20180602_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=system.models.OverwriteFileSystemStorage(location='/media/'), upload_to=system.models.upload_file_name, verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
