# Generated by Django 3.2.4 on 2021-06-10 21:17

from django.db import migrations, models
import system.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20210605_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=system.models.OverwriteFileSystemStorage(location='d:/osobiste/wojtek/inne/projekty/typer-2018/media/'), upload_to=system.models.upload_file_name, verbose_name='Zdjęcie'),
        ),
    ]
