# Generated by Django 2.0.4 on 2018-06-11 14:33

from django.db import migrations, models
import team.models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='vertical_logo',
            field=models.BooleanField(default=False, verbose_name='Czy logo pionowe'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, upload_to=team.models.upload_file_name, verbose_name='Herb / flaga'),
        ),
    ]
