# Generated by Django 3.2.4 on 2021-06-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20180611_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='repeat_logo',
            field=models.BooleanField(default=False, verbose_name='Czy logo ma być powtarzane w obu osiach'),
        ),
    ]
