# Generated by Django 2.0.4 on 2018-05-01 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name': 'Grupa',
                'verbose_name_plural': 'Grupy',
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='GroupTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.SmallIntegerField(verbose_name='Punkty')),
                ('goals_scored', models.SmallIntegerField(verbose_name='Gole strzelone')),
                ('goals_conceded', models.SmallIntegerField(verbose_name='Gole stracone')),
                ('matches', models.SmallIntegerField(verbose_name='Mecze')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='round.Group', verbose_name='Grupa')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team', verbose_name='Drużyna')),
            ],
            options={
                'verbose_name': 'Drużyna w grupie',
                'verbose_name_plural': 'Drużyny w grupie',
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa')),
                ('roundType', models.SmallIntegerField(choices=[(1, 'Faza grupowa'), (2, '1/8 finału'), (3, 'Ćwierćfinał'), (4, 'Półfinał'), (5, 'Finał')], verbose_name='Rodzaj')),
                ('matches', models.ManyToManyField(related_name='rounds', to='match.Match', verbose_name='Mecze')),
            ],
            options={
                'verbose_name': 'Runda',
                'verbose_name_plural': 'Rundy',
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.AddField(
            model_name='group',
            name='teams',
            field=models.ManyToManyField(through='round.GroupTeam', to='team.Team', verbose_name='Drużyny'),
        ),
    ]
