# Generated by Django 2.0.4 on 2018-05-01 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='matches',
        ),
    ]
