# Generated by Django 2.0.4 on 2018-06-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0003_auto_20180610_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupteam',
            name='goals_conceded',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Gole stracone'),
        ),
        migrations.AlterField(
            model_name='groupteam',
            name='goals_scored',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Gole strzelone'),
        ),
        migrations.AlterField(
            model_name='groupteam',
            name='matches',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Mecze'),
        ),
    ]
