# Generated by Django 2.0.4 on 2018-06-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0004_auto_20180611_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupteam',
            name='points',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Punkty'),
        ),
    ]
