# Generated by Django 2.0.4 on 2018-06-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0005_auto_20180611_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupteam',
            name='position',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Pozycja'),
        ),
    ]
