# Generated by Django 2.0.4 on 2018-06-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0006_groupteam_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='roundType',
            field=models.SmallIntegerField(choices=[(1, 'Faza grupowa'), (2, '1/8 finału'), (3, 'Ćwierćfinał'), (4, 'Półfinał'), (5, 'Mecz o 3. miejsce'), (6, 'Finał')], verbose_name='Rodzaj'),
        ),
    ]
