# Generated by Django 2.0.4 on 2018-06-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0007_auto_20180628_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='shortname',
            field=models.CharField(default='', max_length=16, verbose_name='Nazwa skrócona'),
        ),
    ]
