# Generated by Django 2.0.4 on 2018-05-01 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Data i godzina')),
            ],
            options={
                'verbose_name': 'Mecz',
                'verbose_name_plural': 'Mecze',
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular', models.CharField(max_length=5, verbose_name='Wynik w regulaminowym czasie gry')),
                ('et', models.CharField(blank=True, max_length=5, null=True, verbose_name='Wynik w dogrywce')),
                ('penalty', models.CharField(blank=True, max_length=5, null=True, verbose_name='Wynik w rzutach karnych')),
                ('regular_home', models.SmallIntegerField(verbose_name='Gole gospodarzy w regulaminowym czasie gry')),
                ('regular_away', models.SmallIntegerField(verbose_name='Gole gości w regulaminowym czasie gry')),
                ('et_home', models.SmallIntegerField(blank=True, null=True, verbose_name='Gole gospodarzy w dogrywce')),
                ('et_away', models.SmallIntegerField(blank=True, null=True, verbose_name='Gole gości w dogrywce')),
                ('penalty_home', models.SmallIntegerField(blank=True, null=True, verbose_name='Gole gospodarzy w rzutach karnych')),
                ('penalty_away', models.SmallIntegerField(blank=True, null=True, verbose_name='Gole goście w rzutach karnych')),
                ('winner', models.SmallIntegerField(blank=True, choices=[(1, 'Gospodarze'), (2, 'Goście'), (0, 'Remis')], null=True, verbose_name='Zwycięzca')),
            ],
            options={
                'verbose_name': 'Wynik',
                'verbose_name_plural': 'Wyniki',
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.AddField(
            model_name='match',
            name='score',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='match.Score', verbose_name='Wynik'),
        ),
        migrations.AddField(
            model_name='match',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Stadium', verbose_name='Stadion'),
        ),
        migrations.AddField(
            model_name='match',
            name='teamAway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_away', to='team.Team', verbose_name='Goście'),
        ),
        migrations.AddField(
            model_name='match',
            name='teamHome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_home', to='team.Team', verbose_name='Gospodarze'),
        ),
    ]
