# Generated by Django 2.0.4 on 2018-05-01 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0002_remove_round_matches'),
        ('match', '0002_auto_20180501_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='round.Group', verbose_name='Grupa'),
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='round.Round', verbose_name='Runda'),
            preserve_default=False,
        ),
    ]
